//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class RfcVersionHistory
    {
        public int RfcId { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string Comments { get; set; }
        public string RunBy { get; set; }
        public string Action { get; set; }
    }
}
