//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUserInfo
    {
        public int BusinessEntityID { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
